services:
  mysql:
    image: mysql:8.4.0
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib//mysql
    environment:
      MYSQL_ROOT_PASSWORD: supersecret

  php-app:
    build: .
    ports:
      - 8888:8888
    volumes:
      - ./php-app:/app
    depends_on:
      - mysql

volumes:
  db-data: